/**
 * The AI layer's public surface.
 *
 * The planner service should import from here rather than reaching into
 * individual files, so the internal shape of this directory stays ours to
 * change. Nothing here opens a model connection at import time — the provider
 * client is built on the first `getModel()` call.
 */

export {
  AI_MODEL_SETTING_KEY,
  AI_PROVIDERS,
  MODEL_SETTING_TTL_MS,
  buildModel,
  clearModelCache,
  envModelSelection,
  getModel,
  isAiProviderId,
  resolveModelSelection,
  type ActiveModel,
  type AiProviderId,
  type ChatModel,
  type ModelOverride,
  type ModelSelection,
  type ModelSource,
} from './provider'

export {
  ActivitySuggestionSchema,
  BUDGET_BANDS,
  DAY_BLOCK_KINDS,
  DayBlockSchema,
  DayPlanProposalSchema,
  MAX_BLOCKS_PER_DAY,
  MAX_PARTY_SIZE,
  MAX_TEASER_DAY_HIGHLIGHTS,
  MAX_TEASER_SUGGESTED_INTERESTS,
  MAX_TRIP_DAYS,
  MINUTES_IN_DAY,
  TEASER_QUESTIONNAIRE_FIELDS,
  TRANSPORT_PREFERENCES,
  TRIP_PACES,
  TRIP_PURPOSES,
  TeaserDayHighlightSchema,
  TeaserQuestionnaireSchema,
  TeaserResponseSchema,
  TripBriefSchema,
  mergeTripBrief,
  referencedActivityIds,
  teaserCacheKey,
  tripBriefIsPlannable,
  type ActivitySuggestion,
  type BudgetBand,
  type DayBlock,
  type DayBlockKind,
  type DayPlanProposal,
  type TeaserDayHighlight,
  type TeaserQuestionnaire,
  type TeaserResponse,
  type TransportPreference,
  type TripBrief,
  type TripBriefInput,
  type TripPace,
  type TripPurpose,
} from './schemas'

export {
  AiLimitError,
  DEFAULT_AI_LIMITS,
  INSTRUCTION_PATTERNS,
  MAX_LOGGED_TEXT_LENGTH,
  MAX_TOOL_TEXT_LENGTH,
  REDACTION_MARKER,
  STRUCTURAL_PATTERNS,
  SessionBudget,
  aiTimedOut,
  buildMessages,
  inspectText,
  redactDeep,
  redactForLog,
  sanitiseToolOutput,
  sanitiseToolText,
  sanitiseUserText,
  sessionBudgetExhausted,
  systemMessage,
  userMessage,
  withWallClock,
  type AiLimitReason,
  type AiLimits,
  type InjectionPattern,
  type PromptParts,
  type TokenUsageLike,
} from './guard'

export {
  AI_CALL_PURPOSES,
  DEFAULT_USD_TO_BDT_RATE,
  MICRO_BDT_PER_BDT,
  buildUsageRecord,
  describeUsage,
  getModelPrice,
  listModelPrices,
  normaliseUsage,
  registerModelPrice,
  sumUsageRecords,
  toPlannerMessageFields,
  type AiCallPurpose,
  type AiUsageRecord,
  type ModelPrice,
  type NormalisedUsage,
  type UsageRecordInput,
  type UsageTotals,
} from './usage'

export {
  PLANNER_PROMPT_VERSION,
  PROMPT_VERSIONS,
  TEASER_PROMPT_VERSION,
  plannerSystemPrompt,
  plannerSystemPromptV1,
  teaserSystemPrompt,
  teaserSystemPromptV1,
  type EntitlementContext,
  type PlannerPromptContext,
  type PromptSurface,
  type TeaserPromptContext,
} from './prompts'
